// Ajustes por defecto, compartidos entre el script de contenido, el popup y el service worker.
(function (root) {
  const DEFAULTS = {
    enabled: true,
    language: 'auto', // auto (según el navegador) | es | en
    theme: 'auto', // auto | light | dark
    accent: '', // vacío = color del tema; si no, un hex (#rrggbb)
    supporter: false, // personalizaciones desbloqueadas: vienen con el plan pago y se conservan
    centered: true,
    contentWidth: 1040, // px
    fontSize: 16, // px
    fontFamily: '', // vacío = tipografía del sistema
    lineHeight: 1.65,
    autoRefresh: true,
    rememberPosition: true,
    updateCheck: 'daily', // daily | weekly | off: cada cuánto mira si hay versión nueva en GitHub
    wrapCode: true, // las líneas largas de los bloques de código bajan de renglón
    autosave: false,
    autosaveDelay: 2000, // ms después del último cambio
    cloudUrl: '', // servidor de sincronización propio; vacío usa el de la versión, "off" deja la app sin nube
    codeColor: '', // tinte de los bloques de código; vacío = el del tema
    diagramShape: 'round', // round | square: nodos y flechas de los diagramas de flujo
    focusMode: false, // al editar, atenúa todo menos el bloque en el que se escribe
    typewriter: false, // al editar, mantiene el renglón actual a media altura
    refreshInterval: 1000, // ms
    sidebarHidden: false,
    sidebarWidth: 300,
    filesOnlyMarkdown: true,
    filesShowHidden: false,
    customCSS: '',
    plugins: {
      highlight: true,
      emoji: true,
      sub: true,
      sup: true,
      ins: true,
      mark: true,
      abbr: true,
      deflist: true,
      footnote: true,
      tasklists: true,
      alerts: true,
      toc: true,
      katex: true,
      mermaid: true,
      graphviz: true,
      tables: true,
      containers: true,
      frontmatter: true,
      wikilinks: true,
      anchors: true,
      copyCode: true,
      imageViewer: true,
      html: true,
      linkify: true,
      typographer: true,
      breaks: false,
    },
  };

  const PLUGIN_LABELS = {
    highlight: 'Resaltado de código',
    emoji: 'Emoji (:smile:)',
    sub: 'Subíndice (H~2~O)',
    sup: 'Superíndice (x^2^)',
    ins: 'Insertado (++texto++)',
    mark: 'Marcado (==texto==)',
    abbr: 'Abreviaturas',
    deflist: 'Listas de definición',
    footnote: 'Notas al pie',
    tasklists: 'Listas de tareas',
    alerts: 'Alertas ([!NOTE], [!WARNING])',
    toc: 'Índice en el texto ([[toc]])',
    katex: 'Matemática (KaTeX)',
    mermaid: 'Diagramas (Mermaid)',
    graphviz: 'Diagramas (Graphviz, bloque dot)',
    tables: 'Tablas extendidas (celdas combinadas)',
    containers: 'Bloques ::: tip, warning, details',
    frontmatter: 'Cabecera YAML como ficha',
    wikilinks: 'Links [[nombre]] entre archivos',
    anchors: 'Ancla en los títulos',
    copyCode: 'Botón de copiar en bloques de código',
    imageViewer: 'Ampliar imágenes al hacer clic',
    html: 'Permitir HTML en el documento',
    linkify: 'Convertir URLs sueltas en links',
    typographer: 'Tipografía (comillas y guiones)',
    breaks: 'Salto de línea simple = <br>',
  };
  // Qué hace cada plugin, para mostrar al pasar el mouse.
  const PLUGIN_HELP = {
    highlight: "Colorea el código según su lenguaje.",
    emoji: "Convierte :rocket: en un emoji.",
    sub: "H~2~O se ve con el 2 como subíndice.",
    sup: "x^2^ se ve con el 2 como superíndice.",
    ins: "++texto++ se ve subrayado, como agregado.",
    mark: "==texto== se ve resaltado.",
    abbr: "Define una sigla una vez y muestra su significado al pasar el mouse.",
    deflist: "Un término y, debajo, su definición con dos puntos.",
    footnote: "[^1] crea una nota al pie numerada con su vuelta.",
    tasklists: "- [ ] y - [x] se ven como casillas que se pueden tildar.",
    alerts: "> [!NOTE] y > [!WARNING] se ven como avisos de color.",
    toc: "[[toc]] inserta el índice del documento en ese lugar.",
    katex: "$E = mc^2$ y los bloques $$ se dibujan como fórmulas.",
    mermaid: "Un bloque mermaid se dibuja como diagrama.",
    graphviz: "Un bloque dot se dibuja como grafo.",
    tables: "Tablas con celdas combinadas y varias líneas por celda.",
    containers: "::: tip, ::: warning y ::: details arman recuadros.",
    frontmatter: "La cabecera YAML del principio se muestra como una ficha.",
    wikilinks: "[[nombre]] abre el archivo con ese nombre en la carpeta.",
    anchors: "Cada título trae un enlace para copiar su dirección.",
    copyCode: "Un botón en cada bloque de código para copiarlo.",
    imageViewer: "Un clic en una imagen la muestra en grande.",
    html: "Respeta el HTML escrito dentro del documento, ya filtrado.",
    linkify: "Una dirección escrita suelta se vuelve un enlace.",
    typographer: "Comillas tipográficas y guiones más prolijos.",
    breaks: "Un solo Enter corta el renglón, sin dejar una línea en blanco.",
  };


  function merge(saved) {
    const out = Object.assign({}, DEFAULTS, saved || {});
    out.plugins = Object.assign({}, DEFAULTS.plugins, (saved && saved.plugins) || {});
    return out;
  }

  function load() {
    return new Promise((resolve) => {
      chrome.storage.local.get('settings', (r) => resolve(merge(r && r.settings)));
    });
  }

  function save(settings) {
    return new Promise((resolve) => chrome.storage.local.set({ settings }, resolve));
  }

  // Los cambios se encolan: dos patch seguidos no se pisan entre sí.
  let queue = Promise.resolve();
  function patch(partial) {
    queue = queue.then(async () => {
      const cur = await load();
      const next = Object.assign({}, cur, partial);
      if (partial.plugins) next.plugins = Object.assign({}, cur.plugins, partial.plugins);
      await save(next);
      return next;
    });
    return queue;
  }

  const ACCENTS = [
    { name: 'Del tema', value: '' },
    { name: 'Azul', value: '#3b82f6' },
    { name: 'Índigo', value: '#6c7ee1' },
    { name: 'Violeta', value: '#a855f7' },
    { name: 'Rosa', value: '#ec4899' },
    { name: 'Rojo', value: '#ef4444' },
    { name: 'Naranja', value: '#f97316' },
    { name: 'Ámbar', value: '#eab308' },
    { name: 'Turquesa', value: '#14b8a6' },
  ];

  const CODE_COLORS = [
    { name: 'Del tema', value: '' }, { name: 'Azul', value: '#3b82f6' }, { name: 'Violeta', value: '#a855f7' }, { name: 'Verde', value: '#22c55e' },
    { name: 'Ámbar', value: '#eab308' }, { name: 'Naranja', value: '#f97316' }, { name: 'Rosa', value: '#ec4899' },
  ];

  // Tipografías que ya vienen con el sistema, cada una con su respaldo.
  const FONTS = [
    { name: 'SharpMD (Inter)', value: '' },
    { name: 'Del sistema', value: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif' },
    { name: 'Arial', value: 'Arial, Helvetica, sans-serif' },
    { name: 'Calibri', value: 'Calibri, Candara, "Segoe UI", sans-serif' },
    { name: 'Verdana', value: 'Verdana, Geneva, sans-serif' },
    { name: 'Trebuchet MS', value: '"Trebuchet MS", "Lucida Grande", sans-serif' },
    { name: 'Georgia', value: 'Georgia, "Times New Roman", serif' },
    { name: 'Cambria', value: 'Cambria, Georgia, serif' },
    { name: 'Palatino', value: '"Palatino Linotype", Palatino, "Book Antiqua", serif' },
    { name: 'Times New Roman', value: '"Times New Roman", Times, serif' },
    { name: 'Consolas', value: 'Consolas, "Cascadia Mono", Menlo, monospace' },
    { name: 'Courier New', value: '"Courier New", Courier, monospace' },
  ];

  // Idioma. Las claves son el texto en español; EN tiene la traducción. Sin traducción, queda el español.
  const EN = {
      "Carpeta": "Folder",
      "Índice": "Outline",
      "Arrastrar para cambiar el ancho": "Drag to resize",
      "Barra lateral (Alt+Shift+B)": "Sidebar (Alt+Shift+B)",
      "Palabras y caracteres": "Words and characters",
      "Vista": "View",
      "Ver documento": "View document",
      "Ver código fuente": "View source",
      "Copiar Markdown": "Copy Markdown",
      "Copiar con formato (la selección, o todo el documento)": "Copy with formatting (the selection, or the whole document)",
      "Recargar ahora": "Reload now",
      "Imprimir o guardar PDF": "Print or save as PDF",
      "Ajustes": "Settings",
      "Volver arriba": "Back to top",
      "Copiar": "Copy",
      "Enlace a esta sección": "Link to this section",
      "No hay un archivo con ese nombre en la carpeta": "No file with that name in this folder",
      "Copiado con formato": "Copied with formatting",
      "Selección: {w} palabra · {c} caracteres": "Selection: {w} word · {c} characters",
      "Selección: {w} palabras · {c} caracteres": "Selection: {w} words · {c} characters",
      "{w} palabras": "{w} words",
      "Recarga automática activa": "Auto-reload on",
      "Este documento no tiene títulos.": "This document has no headings.",
      "{w} palabras · {m} min · {n} sección": "{w} words · {m} min · {n} section",
      "{w} palabras · {m} min · {n} secciones": "{w} words · {m} min · {n} sections",
      "Avance de lectura": "Reading progress",
      "Plegar o desplegar": "Collapse or expand",
      "No se pudo releer el archivo": "Could not re-read the file",
      "Documento actualizado": "Document updated",
      "Sin cambios": "No changes",
      "Subir a la carpeta superior": "Go up one folder",
      "Leyendo carpeta…": "Reading folder…",
      "No se pudo leer la carpeta. Activá \"Permitir acceso a URL de archivo\" en los detalles de la extensión.": "Could not read the folder. Turn on \"Allow access to file URLs\" in the extension details.",
      "Este servidor no expone el listado de la carpeta.": "This server does not expose the folder listing.",
      "Carpeta sin archivos Markdown.": "No Markdown files in this folder.",
      "Sin coincidencias en {n} archivo": "No matches in {n} file",
      "Sin coincidencias en {n} archivos": "No matches in {n} files",
      ". Se revisaron los primeros {n}.": ". Only the first {n} were checked.",
      "Línea {n}": "Line {n}",
      "y más en este archivo": "and more in this file",
      "Cerrar": "Close",
      "Apariencia": "Appearance",
      "Idioma": "Language",
      "Tema": "Theme",
      "Automático": "Auto",
      "Claro": "Light",
      "Oscuro": "Dark",
      "Color de acento": "Accent color",
      "Otro color": "Custom color",
      "Centrar el contenido": "Center the content",
      "Ajustar las líneas largas del código": "Wrap long lines in code blocks",
      "Ancho del contenido": "Content width",
      "Tamaño de letra": "Font size",
      "Interlineado": "Line height",
      "Tipografía": "Font",
      "Del sistema": "System default",
      "Lectura": "Reading",
      "Edición": "Editing",
      "Documento": "Document",
      "Recargar solo cuando el archivo cambia": "Reload automatically when the file changes",
      "Revisar cada": "Check every",
      "Recordar por dónde iba en cada archivo": "Remember where I left off in each file",
      "Mostrar solo archivos Markdown": "Show Markdown files only",
      "Mostrar archivos y carpetas ocultos": "Show hidden files and folders",
      "Plugins de Markdown": "Markdown plugins",
      "CSS propio": "Custom CSS",
      "Se aplica encima del tema. El documento vive dentro de .markdown-body.": "Applied on top of the theme. The document lives inside .markdown-body.",
      "Restablecer todo": "Reset everything",
      "No se pudo releer el archivo. Recargá la pestaña con F5": "Could not re-read the file. Reload the tab with F5",
      "Actualizaciones": "Updates",
      "Colorea el código según su lenguaje.": "Colors code by its language.",
      "Convierte :rocket: en un emoji.": "Turns :rocket: into an emoji.",
      "H~2~O se ve con el 2 como subíndice.": "H~2~O shows the 2 as a subscript.",
      "x^2^ se ve con el 2 como superíndice.": "x^2^ shows the 2 as a superscript.",
      "++texto++ se ve subrayado, como agregado.": "++text++ shows underlined, as inserted.",
      "==texto== se ve resaltado.": "==text== shows highlighted.",
      "Define una sigla una vez y muestra su significado al pasar el mouse.": "Define an abbreviation once and show its meaning on hover.",
      "Un término y, debajo, su definición con dos puntos.": "A term and, below it, its definition after a colon.",
      "[^1] crea una nota al pie numerada con su vuelta.": "[^1] creates a numbered footnote with a way back.",
      "- [ ] y - [x] se ven como casillas que se pueden tildar.": "- [ ] and - [x] show as boxes you can tick.",
      "> [!NOTE] y > [!WARNING] se ven como avisos de color.": "> [!NOTE] and > [!WARNING] show as colored callouts.",
      "[[toc]] inserta el índice del documento en ese lugar.": "[[toc]] inserts the table of contents at that spot.",
      "$E = mc^2$ y los bloques $$ se dibujan como fórmulas.": "$E = mc^2$ and $$ blocks are drawn as formulas.",
      "Un bloque mermaid se dibuja como diagrama.": "A mermaid block is drawn as a diagram.",
      "Un bloque dot se dibuja como grafo.": "A dot block is drawn as a graph.",
      "Tablas con celdas combinadas y varias líneas por celda.": "Tables with merged cells and several lines per cell.",
      "::: tip, ::: warning y ::: details arman recuadros.": "::: tip, ::: warning and ::: details make boxes.",
      "La cabecera YAML del principio se muestra como una ficha.": "The YAML header at the top shows as a card.",
      "[[nombre]] abre el archivo con ese nombre en la carpeta.": "[[name]] opens the file with that name in the folder.",
      "Cada título trae un enlace para copiar su dirección.": "Each heading gets a link to copy its address.",
      "Un botón en cada bloque de código para copiarlo.": "A button on each code block to copy it.",
      "Un clic en una imagen la muestra en grande.": "A click on an image shows it large.",
      "Respeta el HTML escrito dentro del documento, ya filtrado.": "Keeps the HTML written in the document, already filtered.",
      "Una dirección escrita suelta se vuelve un enlace.": "A bare address becomes a link.",
      "Comillas tipográficas y guiones más prolijos.": "Typographic quotes and tidier dashes.",
      "Un solo Enter corta el renglón, sin dejar una línea en blanco.": "A single Enter breaks the line, with no blank line needed.",
      "pronto": "soon", "Gratis": "Free", "Pago": "Paid", "mes": "month", "año": "year", "Plan": "Plan",
      "Todo el editor": "The whole editor", "Hasta 10 notas en la nube": "Up to 10 notes in the cloud", "Los colores, la tipografía y el CSS propio vienen con el plan pago.": "Colors, the font and custom CSS come with the paid plan.", "Ver planes": "See plans", "Volver a lo que tenía": "Back to what I had", "Agregar": "Add", "Paso": "Step", "Pregunta": "Question", "Flecha": "Arrow", "Flecha con texto": "Arrow with a label", "Las notas nuevas se guardan en este navegador": "New notes are saved in this browser", "Guardarlas en una carpeta": "Save them to a folder", "Administrar la suscripción": "Manage subscription", "Qué es SharpMD": "About SharpMD",
      "Notas en el navegador y en tu disco, sin límite": "Notes in the browser and on your disk, no limit",
      "Notas en la nube sin límite": "Unlimited notes in the cloud", "Compartir y editar entre varios": "Share and edit together",
      "Conectar una IA por MCP": "Connect an AI over MCP", "Historial de versiones de 30 días": "30-day version history",
      "Colores, tipografía y CSS propio": "Colors, typeface and custom CSS", "Es tu plan actual.": "This is your current plan.",
      "Notas en la nube": "Notes in the cloud", "{n} de {m}": "{n} of {m}",
      "Compartido": "Shared",
      "Ese enlace ya no existe.": "That link no longer exists.",
      "Esta nota es de solo lectura": "This note is read-only", "Se sumaron los cambios de otra persona": "Someone else's changes were merged in",
      "También acá: {a}": "Also here: {a}", "Compartir": "Share", "Solo quien creó la nota puede hacer eso.": "Only the person who created the note can do that.",
      "Compartir es parte del plan pago.": "Sharing is part of the paid plan.", "Con otra cuenta": "With another account",
      "correo de la otra persona": "the other person's email", "Puede editar": "Can edit", "Solo ver": "View only",
      "Compartir toda la carpeta \"{a}\"": "Share the whole \"{a}\" folder", "Con un enlace de solo lectura": "With a read-only link",
      "contraseña (opcional)": "password (optional)", "Crear enlace": "Create link", "Ese es tu propio correo.": "That is your own email.",
      "Quitar": "Remove", "Enlace con contraseña": "Link with a password", "Enlace abierto": "Open link",
      "Lectura y edición": "Reading and editing", "Plugins": "Plugins", "Cuenta": "Account",
      "Plan pago": "Paid plan", "Plan gratis": "Free plan", "Sin conexión": "Offline",
      "Sin conexión: los cambios quedan en este navegador y se suben al volver": "Offline: changes stay in this browser and upload when the connection is back",
      "Sin conexión. Esta es la copia guardada en este navegador": "Offline. This is the copy saved in this browser",
      "Sin conexión, y \"{a}\" no tiene copia en este navegador.": "Offline, and \"{a}\" has no copy in this browser.",
      "La nota cambió en la nube. Lo que escribiste sin conexión quedó en \"{a}\"": "The note changed in the cloud. What you wrote offline was kept in \"{a}\"",
      "sin conexión": "offline",
      "Llegaste al límite de notas del plan gratis. El plan pago no tiene límite.": "You reached the note limit of the free plan. The paid plan has no limit.",
      "Esta carpeta es de solo lectura": "This folder is read-only", "Nueva carpeta": "New folder", "carpeta": "folder",
      "Nombre de la carpeta nueva": "Name for the new folder", "Ya hay una carpeta con ese nombre": "A folder with that name already exists",
      "Guardando en la nube…": "Saving to the cloud…", "Sincronizado con la nube": "Synced with the cloud",
      "Esta nota no está en la nube. Clic para subirla": "This note is not in the cloud. Click to upload it",
      "Sincronización apagada. Clic para entrar a tu cuenta": "Sync is off. Click to sign in",
      "Llegaste al límite de notas del plan gratis.": "You reached the note limit of the free plan.", "No se pudo subir la nota.": "Could not upload the note.",
      "Historial de versiones": "Version history", "El historial de versiones es parte del plan pago.": "Version history is part of the paid plan.",
      "Todavía no hay versiones anteriores de esta nota.": "There are no earlier versions of this note yet.",
      "Restaurar esta versión": "Restore this version", "Versión restaurada. Ctrl+Z la deshace": "Version restored. Ctrl+Z undoes it",
      "Lista con viñetas": "Bulleted list", "Insertar imagen": "Insert image", "Dirección o ruta": "Address or path", "Elegir un archivo": "Choose a file",
      "Descripción (para quien no ve la imagen)": "Description (for people who cannot see the image)", "Tamaño": "Size",
      "Original": "Original", "Chica": "Small", "Mediana": "Medium", "Grande": "Large",
      "Ese archivo no es una imagen que se pueda insertar.": "That file is not an image that can be inserted.",
      "La imagen pesa más de 10 MB.": "The image is larger than 10 MB.",
      "Sin una carpeta abierta la imagen va dentro del documento, y esta es muy grande para eso. Abrí la carpeta desde SharpMD, o usá una dirección web.": "Without an open folder the image goes inside the document, and this one is too large for that. Open the folder from SharpMD, or use a web address.",
      "Falta la dirección o el archivo.": "The address or the file is missing.", "Esa dirección no sirve para una imagen.": "That address cannot be used for an image.",
      "Color de los bloques de código": "Code block color", "Vista previa": "Preview", "Notas de lanzamiento": "Launch notes", "Así se ve el texto de tus documentos con esta letra, este tamaño y este interlineado.": "This is how the text of your documents looks with this font, size and line height.", "Forma de los diagramas": "Diagram shape", "Redondeados": "Rounded", "Rectos": "Straight",
      "Verde": "Green",
      "Nube": "Cloud", "en la nube": "in the cloud", "Guardado en la nube": "Saved to the cloud",
      "Entrá a tu cuenta para abrir las notas de la nube.": "Sign in to open your cloud notes.",
      "Llegaste al límite de notas del plan gratis. Esta no se guardó en la nube": "You reached the note limit of the free plan. This one was not saved to the cloud",
      "Sin conexión. Se guarda cuando vuelva": "Offline. It will save when the connection is back",
      "Ese correo no parece válido.": "That email does not look valid.", "Recién pediste un código. Esperá {n} segundos para pedir otro.": "You just asked for a code. Wait {n} seconds to ask for another.",
      "Se pidieron demasiados códigos. Si recién pediste uno, esperá 30 segundos; si no, probá de nuevo en una hora.": "Too many codes were requested. If you just asked for one, wait 30 seconds. If not, try again in an hour.",
      "Demasiados códigos equivocados. Pedí un código nuevo; si tampoco entra, probá de nuevo en una hora.": "Too many wrong codes. Ask for a new code. If that one fails too, try again in an hour.",
      "Donde ya entraste, la sesión sigue abierta.": "Devices that are already signed in stay signed in.",
      "No se pudo enviar el correo. Probá de nuevo en unos minutos.": "The email could not be sent. Try again in a few minutes.",
      "Código de seis dígitos": "Six-digit code", "Cambiar el correo o pedir otro código": "Change the email or get a new code",
      "Este navegador no deja escribir sobre el archivo: al guardar se descarga una copia.": "This browser cannot write to the file: saving downloads a copy.",
      "Demasiadas contraseñas equivocadas. Probá de nuevo en 10 minutos.": "Too many wrong passwords. Try again in 10 minutes.",
      "Fórmula en línea": "Inline formula", "Elegí solo texto para hacer una fórmula.": "Select plain text only to make a formula.",
      "Versión nueva: {v}": "New version: {v}",
      "Empezá una nota nueva o abrí una que ya tengas.": "Start a new note or open one you already have.",
      "Modo edición: tocá un texto para cambiarlo": "Edit mode: tap any text to change it",
      "El plan gratis llega a 10 notas en la nube. Esta quedó guardada en este navegador.": "The free plan holds 10 cloud notes. This one is saved in this browser.",
      "Llegaste al tope de tokens. Revocá uno para crear otro.": "You reached the token limit. Revoke one to create another.",
      "Llegaste al tope de lo que se puede compartir. Quitá algo para sumar más.": "You reached the sharing limit. Remove something to add more.",
      "Esta nota ya no está en la nube.": "This note is no longer in the cloud.",
      "Copiá el enlace ahora: no se vuelve a mostrar.": "Copy the link now: it is not shown again.",
      "Ese código no coincide.": "That code does not match.", "El código venció. Pedí otro.": "The code expired. Ask for another one.",
      "No hay conexión con el servidor.": "Cannot reach the server.",
      "Conectar una IA es parte del plan pago.": "Connecting an AI is part of the paid plan.", "No se pudo completar. Probá de nuevo.": "Could not complete it. Try again.",
      "Te mandamos un código a {a}.": "We sent a code to {a}.", "Entrar": "Sign in", "tu correo": "your email", "Enviar código": "Send code",
      "Conectar una IA": "Connect an AI", "Salir": "Sign out",
      "Copiá estos datos ahora: el token no se vuelve a mostrar.": "Copy these now: the token is not shown again.",
      "La cuenta se maneja desde la app de SharpMD.": "Your account lives in the SharpMD app.", "Abrir SharpMD": "Open SharpMD",
      "IA": "AI", "Avanzado": "Advanced", "Uso mi propio servidor": "I use my own server", "Usar SharpMD sin nube": "Use SharpMD without the cloud", "Dirección del servidor": "Server address",
      "{n}, sin límite": "{n}, no limit", "1 nota, sin límite": "1 note, no limit", "{n} notas, sin límite": "{n} notes, no limit",
      "La nube está apagada: SharpMD funciona sin cuenta y sin sincronizar.": "The cloud is off: SharpMD works with no account and no sync.", "Prender la nube": "Turn the cloud on",
      "Abrir la carpeta Nube": "Open the Cloud folder", "Abrir la nube": "Open the cloud",
      "Una IA que hable MCP, como Claude, lee y escribe tus notas de la nube.": "An AI that speaks MCP, like Claude, reads and writes your cloud notes.",
      "Tokens": "Tokens", "creado el {a}": "created {a}", "usado el {a}": "used {a}", "sin usar": "never used", "Todavía no hay tokens.": "No tokens yet.",
      "Crear un token": "Create a token", "Revocar": "Revoke", "Copiado": "Copied",
      "La nube está apagada: sin ella no hay notas para conectar.": "The cloud is off: without it there are no notes to connect.",
      "Entrá a tu cuenta para conectar una IA.": "Sign in to connect an AI.", "Entrá a tu cuenta para pasar al plan pago.": "Sign in to move to the paid plan.",
      "La nube está apagada: los planes son de la cuenta de la nube.": "The cloud is off: plans belong to the cloud account.",
      "Esperando la confirmación del pago…": "Waiting for the payment confirmation…", "Pago confirmado. Ya tenés el plan pago.": "Payment confirmed. You are on the paid plan.",
      "La confirmación del pago todavía no llegó. Volvé a revisar en unos minutos.": "The payment confirmation has not arrived yet. Check again in a few minutes.", "Revisar ahora": "Check now",
      "Enviar comentarios": "Send feedback", "Qué pasó, o qué te gustaría que cambie": "What happened, or what you would like to change",
      "tu correo, si querés respuesta (opcional)": "your email, if you want a reply (optional)", "Enviar": "Send", "Enviado": "Sent",
      "Escribí al menos unas palabras.": "Write at least a few words.", "Llegaste al tope de envíos por ahora. Probá más tarde.": "You reached the sending limit for now. Try again later.",
      "Desde acá no se pudo enviar.": "It could not be sent from here.", "Escribinos a {a}.": "Write to us at {a}.",
      "Escribí tu correo.": "Enter your email.", "El correo no lleva espacios.": "An email has no spaces.",
      "Ese correo no parece válido. Tiene que ser como nombre@dominio.com.": "That email does not look valid. It should look like name@domain.com.", "El código son seis dígitos.": "The code is six digits.",
      "Tablero": "Board", "Por hacer": "To do", "En curso": "In progress", "Hecho": "Done", "Primera tarjeta": "First card",
      "Tarjeta": "Card", "Tarjeta nueva": "New card", "Eliminar la tarjeta": "Delete the card", "Eliminar la columna": "Delete the column",
      "Totales": "Totals", "Agregar una fila que suma cada columna": "Add a row that sums each column",
      "Esta tabla ya tiene una fila de totales": "This table already has a totals row",
      "No hay columnas con números para sumar": "There are no columns with numbers to add up",
      "Fila de totales agregada. Cambiá =sum por =avg, =min, =max, =count o =median": "Totals row added. Change =sum to =avg, =min, =max, =count or =median",
      "Guardando…": "Saving…",
      "En este navegador": "In this browser", "en este navegador": "in this browser",
      "Guardado en este navegador": "Saved in this browser",
      "Guardar como archivo en el disco (Ctrl+S)": "Save as a file on disk (Ctrl+S)",
      "Se descargó una copia. La nota sigue guardada en este navegador": "A copy was downloaded. The note stays saved in this browser",
      "Opciones del bloque: mover, duplicar, eliminar": "Block options: move, duplicate, delete", "Eliminar el diagrama": "Delete the diagram",
      "Ver": "View", "Editar": "Edit", "SharpMD (Inter)": "SharpMD (Inter)",
      "Archivos": "Files", "Cambios sin guardar": "Unsaved changes", "Todo guardado": "All saved",
      "Guardado · autoguardado activo": "Saved · auto-save on",
      "Las notas nuevas se guardan en": "New notes are saved to", "Cambiar": "Change",
      "Cambio deshecho. Ctrl+Y lo rehace": "Change undone. Ctrl+Y redoes it", "Cambio rehecho": "Change redone", "No hay cambios para rehacer": "Nothing to redo",
      "Abrir": "Open", "Nuevo": "New", "Versión {v}": "Version {v}", "Al día": "Up to date", "Buscar actualizaciones": "Check for updates",
      "Hay una versión nueva: {v}": "New version available: {v}",
      "Descargá el ZIP, reemplazá la carpeta de la extensión y tocá Aplicar.": "Download the ZIP, replace the extension folder and click Apply.",
      "No se pudo consultar": "Could not check",
      "Nombre del archivo nuevo": "Name for the new file", "nota": "note",
      "Ese nombre tiene caracteres que no se pueden usar": "That name has characters that cannot be used",
      "Ya hay un archivo con ese nombre": "A file with that name already exists",
      "No se pudo crear el archivo": "Could not create the file", "No se pudo renombrar": "Could not rename", "No se pudo eliminar": "Could not delete",
      "Nuevo archivo acá": "New file here", "Nuevo archivo": "New file", "Renombrar": "Rename",
      "Nombre del archivo": "File name", "Doble clic o F2 para cambiar el nombre": "Double-click or press F2 to rename",
      "No se pudo mover": "Could not move",
      "Para pegar imágenes abrí la carpeta desde la página de SharpMD": "To paste images, open the folder from the SharpMD page",
      "imagen": "image", "Imagen guardada en {a}": "Image saved to {a}", "No se pudo guardar la imagen": "Could not save the image",
      "Sin coincidencias": "No matches", "Reemplazado. Quedan {n}": "Replaced. {n} left",
      "{n} reemplazo. Ctrl+Z lo deshace": "{n} replacement. Ctrl+Z undoes it", "{n} reemplazos. Ctrl+Z los deshace": "{n} replacements. Ctrl+Z undoes them",
      "Reemplazar con": "Replace with", "Uno": "One", "Todos": "All",
      "Reemplazar la primera coincidencia": "Replace the first match", "Reemplazar todas": "Replace all",
      "HTML descargado": "HTML downloaded", "Exportar a HTML": "Export to HTML",
      "Modo foco: atenuar lo que no estoy escribiendo": "Focus mode: dim what I am not writing",
      "Máquina de escribir: mantener el renglón a media altura": "Typewriter: keep the current line at mid height",
      "Este tipo de archivo no se puede mostrar.": "This kind of file cannot be shown.",
      "Se muestran las primeras {n} filas.": "Showing the first {n} rows.",
      "Las imágenes no se editan acá": "Images are not edited here",
      "Editar diagrama": "Edit diagram", "Plantillas": "Templates", "Ver la sintaxis": "Syntax reference",
      "Flujo": "Flowchart", "Secuencia": "Sequence", "Estados": "States", "Clases": "Classes", "Datos": "Data", "Torta": "Pie",
      "Mapa mental": "Mind map", "Línea de tiempo": "Timeline", "¿Sirve?": "Works?", "Sí": "Yes", "Seguir": "Continue", "Corregir": "Fix",
      "Usuario": "User", "Servidor": "Server", "Pide algo": "Asks for something", "Consulta": "Query", "Respuesta": "Response", "Resultado": "Result",
      "Borrador": "Draft", "Revisión": "Review", "Publicado": "Published", "Pedido": "Order", "Cliente": "Customer", "Plan": "Plan",
      "Diseño": "Design", "Prototipo": "Prototype", "Desarrollo": "Development", "Primera versión": "First version", "Reparto": "Split",
      "Tema central": "Topic", "Idea": "Idea", "Detalle": "Detail", "Historia": "History", "Lanzamiento": "Launch",
      "Copiar el código del diagrama": "Copy the diagram code", "Descargar como SVG": "Download as SVG", "Ampliar": "Enlarge",
      "Código del diagrama copiado": "Diagram code copied", "diagrama": "diagram",
      "Escribí acá, o / para insertar": "Type here, or / to insert",
      "Título 1": "Heading 1", "Título 2": "Heading 2", "Título 3": "Heading 3", "Título 4": "Heading 4",
      "Lista": "List", "Lista numerada": "Numbered list", "Tarea": "Task", "Lista de tareas": "Task list", "Cita": "Quote",
      "Ítem nuevo": "New item", "Párrafo": "Paragraph", "Tabla": "Table", "Bloque de código": "Code block",
      "Diagrama": "Diagram", "Fórmula": "Formula", "Aviso": "Callout", "Imagen": "Image", "Separador": "Divider",
      "Columna": "Column", "Inicio": "Start", "Fin": "End", "Texto del aviso": "Callout text",
      "Bloque eliminado. Ctrl+Z lo deshace": "Block deleted. Ctrl+Z brings it back",
      "Insertar debajo": "Insert below", "Insertar": "Insert", "Convertir en": "Turn into", "Este bloque": "This block",
      "Subir": "Move up", "Bajar": "Move down", "Duplicar": "Duplicate", "Eliminar": "Delete",
      "Cambio deshecho": "Change undone", "No hay más cambios para deshacer": "Nothing left to undo",
      "Seguir escribiendo": "Keep writing",
      "Insertar un bloque (también con clic derecho)": "Insert a block (right-click works too)",
      "Abrir otro archivo o carpeta": "Open another file or folder",
      "Abrir archivo": "Open file",
      "Abrir carpeta": "Open folder",
      "También podés arrastrar un archivo o una carpeta a esta ventana.": "You can also drag a file or a folder onto this window.",
      "Recientes": "Recent",
      "También podés arrastrar un archivo a esta ventana. Este navegador no deja escribir sobre el archivo: al guardar se descarga una copia.": "You can also drag a file onto this window. This browser cannot write to the file: saving downloads a copy.",
      "Quitar de la lista": "Remove from the list",
      "Esa carpeta no tiene archivos Markdown.": "That folder has no Markdown files.",
      "No se pudo abrir. Probá de nuevo.": "Could not open it. Try again.",
      "Chrome pide que confirmes el acceso antes de seguir.": "Chrome asks you to confirm access before continuing.",
      "Continuar": "Continue",
      "Ese acceso ya no está guardado. Abrí el archivo o la carpeta de nuevo.": "That access is no longer saved. Open the file or folder again.",
      "No se encontró \"{a}\".": "Could not find \"{a}\".",
      "Buscar versiones nuevas": "Check for new versions",
      "Por día": "Daily",
      "Por semana": "Weekly",
      "Nunca": "Never",
      "Versión instalada: {v}": "Installed version: {v}",
      "Buscar ahora": "Check now",
      "Buscando…": "Checking…",
      "Ya tenés la última versión ({v})": "You have the latest version ({v})",
      "No se pudo consultar GitHub": "Could not reach GitHub",
      "Lo único que se consulta es el número de versión publicado en GitHub. No se manda ningún dato.": "The only thing fetched is the version number published on GitHub. No data is sent.",

      "Tenés la {v}.": "You have {v}.",
      "Descargar": "Download",
      "Aplicar": "Apply",
      "Descargá el ZIP, reemplazá con su contenido la carpeta de la extensión y tocá Aplicar. Si la clonaste con git, alcanza con git pull y Aplicar.": "Download the ZIP, replace the extension folder with its contents and click Apply. If you cloned it with git, run git pull and click Apply.",
      "Ahora no": "Not now",
      "Permiso para guardar": "Permission to save",
      "Chrome pide que elijas dónde puede escribir SharpMD. Elegí la carpeta de este archivo una sola vez y vas a poder guardar todo lo que haya adentro, sin que vuelva a preguntar.": "Chrome asks you to choose where SharpMD may write. Pick this file's folder once and you can save everything inside it, without being asked again.",
      "Elegir la carpeta": "Choose the folder",
      "Solo este archivo": "This file only",
      "Cancelar": "Cancel",
      "Esa carpeta no contiene \"{a}\". Elegí la carpeta donde está el archivo, o una que la contenga.": "That folder does not contain \"{a}\". Choose the folder where the file is, or one that contains it.",
      "No se pudo obtener el permiso. Probá de nuevo.": "Could not get the permission. Try again.",

      "Guardar y volver a solo lectura": "Save and go back to read only",
      "Estás viendo el documento": "You are viewing the document",
      "Estás editando el documento": "You are editing the document",
      "Editar el documento": "Edit the document",
      "Modo": "Mode",

      "Guardar (Ctrl+S)": "Save (Ctrl+S)",
      "Guardar (Ctrl+S). Hay cambios sin guardar": "Save (Ctrl+S). There are unsaved changes",
      "Negrita (Ctrl+B)": "Bold (Ctrl+B)",
      "Cursiva (Ctrl+I)": "Italic (Ctrl+I)",
      "Tachado": "Strikethrough",
      "Código": "Code",
      "Enlace": "Link",
      "Enlace (Ctrl+K)": "Link (Ctrl+K)",
      "Copiado": "Copied",
      "Buscar en la carpeta": "Search in folder",
      "Editar acá": "Edit here",
      "Copiar el bloque": "Copy block",
      "Copiar el enlace a esta sección": "Copy link to this section",
      "Sin cuenta": "No account",
      "Con cuenta": "With an account",
      "Todo el editor, tus archivos del disco y las notas guardadas en este navegador.": "The whole editor, your files on disk and the notes saved in this browser.",
      "Notas en la nube (10 gratis). Compartir, historial y conexión con una IA en el plan pago.": "Cloud notes (10 free). Sharing, history and AI connection on the paid plan.",
      "Editar el enlace": "Edit link",
      "Ahora lleva a": "Now points to",
      "Destino": "Destination",
      "Este documento": "This document",
      "Otro archivo": "Another file",
      "Dirección web": "Web address",
      "Filtrar títulos": "Filter headings",
      "Filtrar archivos": "Filter files",
      "Marcar en el documento": "Pick in the document",
      "Quitar el enlace": "Remove link",
      "Cambiar": "Change",
      "Ningún título coincide.": "No heading matches.",
      "Ningún archivo coincide.": "No file matches.",
      "No se pudo leer la carpeta.": "Could not read the folder.",
      "No hay otros archivos Markdown en esta carpeta.": "There are no other Markdown files in this folder.",
      "Ver sus títulos": "Show its headings",
      "Leyendo…": "Reading…",
      "Este archivo no tiene títulos.": "This file has no headings.",
      "Falta la dirección.": "The address is missing.",
      "Esa dirección no sirve para un enlace.": "That address does not work for a link.",
      "Hacé clic en el título al que va el enlace": "Click the heading the link should go to",
      "No se encontró la sección \"{a}\".": "Section \"{a}\" was not found.",
      "Quitar formato": "Clear formatting",
      "Fila": "Row",
      "Columna": "Column",
      "Guardá una vez con Ctrl+S para activar el guardado automático": "Save once with Ctrl+S to turn on auto-save",
      "Modo edición: hacé clic en un texto o una celda para cambiarlo": "Edit mode: click any text or cell to change it",
      "Este bloque se edita desde la vista de código": "This block is edited from the source view",
      "Esta tabla se edita desde la vista de código": "This table is edited from the source view",
      "Sin cambios para guardar": "Nothing to save",
      "Este navegador no deja escribir el archivo: se descargó una copia": "This browser cannot write the file: a copy was downloaded",
      "Guardado": "Saved",
      "No se pudo guardar": "Could not save",
      "El archivo cambió en el disco. Tus cambios sin guardar se mantienen": "The file changed on disk. Your unsaved changes are kept",
      "Guardar solo mientras edito": "Auto-save while I edit",
      "Guardar a los": "Save after",
      "Apoyar el proyecto": "Support the project",
      "Nota": "Note",
      "Consejo": "Tip",
      "Importante": "Important",
      "Advertencia": "Warning",
      "Precaución": "Caution",
      "Información": "Info",
      "Peligro": "Danger",
      "Detalles": "Details",
      "Resaltado de código": "Code highlighting",
      "Emoji (:smile:)": "Emoji (:smile:)",
      "Subíndice (H~2~O)": "Subscript (H~2~O)",
      "Superíndice (x^2^)": "Superscript (x^2^)",
      "Insertado (++texto++)": "Inserted (++text++)",
      "Marcado (==texto==)": "Highlighted (==text==)",
      "Abreviaturas": "Abbreviations",
      "Listas de definición": "Definition lists",
      "Notas al pie": "Footnotes",
      "Listas de tareas": "Task lists",
      "Alertas ([!NOTE], [!WARNING])": "Alerts ([!NOTE], [!WARNING])",
      "Índice en el texto ([[toc]])": "Inline table of contents ([[toc]])",
      "Matemática (KaTeX)": "Math (KaTeX)",
      "Diagramas (Mermaid)": "Diagrams (Mermaid)",
      "Diagramas (Graphviz, bloque dot)": "Diagrams (Graphviz, dot block)",
      "Tablas extendidas (celdas combinadas)": "Extended tables (merged cells)",
      "Bloques ::: tip, warning, details": "Blocks ::: tip, warning, details",
      "Cabecera YAML como ficha": "YAML front matter as a card",
      "Links [[nombre]] entre archivos": "[[name]] links between files",
      "Ancla en los títulos": "Heading anchors",
      "Botón de copiar en bloques de código": "Copy button on code blocks",
      "Ampliar imágenes al hacer clic": "Click to enlarge images",
      "Permitir HTML en el documento": "Allow HTML in the document",
      "Convertir URLs sueltas en links": "Turn bare URLs into links",
      "Tipografía (comillas y guiones)": "Typography (quotes and dashes)",
      "Salto de línea simple = <br>": "Single line break = <br>",
      "Del tema": "Theme default",
      "Azul": "Blue",
      "Índigo": "Indigo",
      "Violeta": "Purple",
      "Rosa": "Pink",
      "Rojo": "Red",
      "Naranja": "Orange",
      "Ámbar": "Amber",
      "Turquesa": "Teal",
      "Recarga automática": "Auto-reload",
      "Auto": "Auto",
      "Falta un permiso para abrir archivos locales.": "A permission is missing to open local files.",
      "En los detalles de la extensión, activá \"Permitir acceso a URL de archivo\".": "In the extension details, turn on \"Allow access to file URLs\".",
      "Abrir los detalles": "Open details",
      "Comentar para la IA": "Comment for the AI", "Comentarios para la IA": "Comments for the AI", "Comentario para la IA": "Comment for the AI",
      "{n} comentarios para la IA": "{n} comments for the AI", "Qué querés que cambie": "What you want changed",
      "Escribí qué querés que cambie.": "Write what you want changed.",
      "La nota no se pudo guardar. El comentario no se envió.": "The note could not be saved. The comment was not sent.",
      "Hay demasiados comentarios abiertos. Borrá alguno o esperá a que la IA los resuelva.": "Too many open comments. Delete some or wait for the AI to resolve them.",
      "Los comentarios para la IA son parte del plan pago.": "Comments for the AI are part of the paid plan.",
      "La IA conectada los lee cuando le pedís que revise los comentarios.": "The connected AI reads them when you ask it to review the comments.",
      "Todavía no hay comentarios en esta nota.": "No comments on this note yet.",
      "Abiertos": "Open", "Resueltos": "Resolved", "Respuesta de la IA": "Reply from the AI", "Resuelto el {a}": "Resolved {a}",
      "Comentario enviado": "Comment sent", "Comentario borrado": "Comment deleted", "Borrar": "Delete", "Ver todos": "See all",
      "La IA resolvió un comentario": "The AI resolved a comment", "La IA resolvió {n} comentarios": "The AI resolved {n} comments",
      "Ir a esa parte de la nota": "Go to that part of the note", "Ese texto ya no está en la nota": "That text is no longer in the note",
      "Todas las notas": "All notes", "Carpeta {a}": "Folder {a}",
      "Falta el permiso para abrir \"{a}\".": "Permission to open \"{a}\" is missing.",
      "No se pudieron guardar los cambios de \"{a}\".": "The changes to \"{a}\" could not be saved.",
      "Salir sin guardar": "Leave without saving",
      "Aceptar": "OK",
      "Escribí un nombre.": "Type a name.",
      "Arrastrar para cambiar el alto": "Drag to resize",
      "Crear": "Create",
      "Crear acá": "Create here",
      "Abrir otra carpeta o archivo": "Open another folder or file",
      "Buscar en la nota y en los archivos": "Search this note and your files",
      "En el disco": "On disk",
      "En la nube": "In the cloud",
      "Entrar para ver tus notas": "Sign in to see your notes",
      "No se pudo leer esta carpeta.": "This folder could not be read.",
      "Creá una nota con el botón +.": "Create a note with the + button.",
      "En esta nota": "In this note",
      "Buscando en los archivos…": "Searching your files…",
      "Nota en blanco": "Blank note",
      "Nueva nota": "New note",
      "Elegí una nota de la izquierda o empezá una nueva.": "Pick a note on the left or start a new one.",
      "No se pudo crear la carpeta": "The folder could not be created",
      "Día a día": "Day to day",
      "Proyectos": "Projects",
      "Equipo": "Team",
      "Producto y desarrollo": "Product and development",
      "Personal": "Personal",
      "Desde una plantilla": "From a template",
      "Desde una plantilla…": "From a template…",
      "Filtrar plantillas": "Filter templates",
      "Crear nota": "Create note",
      "Ninguna plantilla coincide.": "No template matches.",
      "¿Eliminar \"{a}\"?": "Delete \"{a}\"?",
      "No se puede deshacer.": "This cannot be undone.",
      "Con \"/\" se mueve a una carpeta": "Use \"/\" to move it into a folder",
      "¿Subir \"{a}\" a la nube?": "Upload \"{a}\" to the cloud?",
      "Queda una copia sincronizada; el archivo de acá no se toca.": "A synced copy is kept; the file here is left untouched.",
      "Subir a la nube": "Upload",
      "¿Revocar este token?": "Revoke this token?",
      "La IA que lo usa deja de entrar.": "The AI using it loses access.",
      "¿Eliminar la columna \"{a}\"?": "Delete the column \"{a}\"?",
      "Se eliminan también sus tarjetas.": "Its cards are deleted too.",
      "El contenido no coincide": "The content does not match",
      "En esa carpeta hay un archivo con el mismo nombre, pero su contenido no coincide con el que tenés abierto.": "That folder has a file with the same name, but its content does not match the one you have open.",
      "Guardar sobre ese archivo": "Save over that file",
      "Elegiste otro archivo": "You picked another file",
      "Elegiste \"{a}\" y el documento abierto es \"{b}\".": "You picked \"{a}\" and the open document is \"{b}\".",
      "Guardar sobre el archivo elegido": "Save over the picked file",
      "Nota protegida": "Protected note",
      "Contraseña": "Password",
      "Escribí la contraseña.": "Type the password.",
      "Esa contraseña no coincide.": "That password does not match.",
      "Crear cuenta o entrar": "Sign up or sign in", "{n} de {m} notas": "{n} of {m} notes",
      "Más acciones": "More actions",
      "Nube: compartir, historial y más": "Cloud: share, history and more",
      "Subir esta nota a la nube": "Upload this note to the cloud",
      "Entrar a la cuenta": "Sign in",
      "Insertar un bloque": "Insert a block",
      // La cuenta de la búsqueda se arma en dos mitades (content.js): estas cuatro claves no aparecen enteras en el código.
      "{t} coincidencia en {f} archivo (de {n})": "{t} match in {f} file (of {n})",
      "{t} coincidencia en {f} archivos (de {n})": "{t} match in {f} files (of {n})",
      "{t} coincidencias en {f} archivo (de {n})": "{t} matches in {f} file (of {n})",
      "{t} coincidencias en {f} archivos (de {n})": "{t} matches in {f} files (of {n})",
      "Copiar con formato": "Copy with formatting",
      "Pasos y decisiones unidos por flechas": "Steps and decisions joined by arrows",
      "Mensajes entre participantes, en orden": "Messages between participants, in order",
      "Los estados por los que pasa algo": "The states something goes through",
      "Clases con sus atributos y relaciones": "Classes with their attributes and relations",
      "Entidades de una base y cómo se relacionan": "Database entities and how they relate",
      "Tareas en el tiempo, por sección": "Tasks over time, by section",
      "Partes de un total": "Parts of a whole",
      "Ideas que salen de un tema central": "Ideas branching from a central topic",
      "Hechos ordenados por fecha": "Events ordered by date",
      "nombre": "name",
      "CLIENTE": "CUSTOMER",
      "PEDIDO": "ORDER",
      "hace": "places",
      "contiene": "contains",
      "Color de un nodo": "Color one node",
      "Participante": "Participant",
      "Mensaje": "Message",
      "Bucle": "Loop",
      "Estado": "State",
      "Transición": "Transition",
      "Clase": "Class",
      "Atributo": "Attribute",
      "Método": "Method",
      "Relación": "Relation",
      "Entidad": "Entity",
      "Sección": "Section",
      "Hito": "Milestone",
      "Porción": "Slice",
      "Rama": "Branch",
      "Subrama": "Sub-branch",
      "Período": "Period",
      "Evento": "Event",
      "Nodo": "Node",
      "Arista": "Edge",
      "Paso nuevo": "New step",
      "¿Pregunta?": "Question?",
      "texto": "text",
      "Nombre": "Name",
      "Cada vez": "Every time",
      "Estado nuevo": "New state",
      "atributo": "attribute",
      "metodo": "method",
      "usa": "uses",
      "ENTIDAD": "ENTITY",
      "tiene": "has",
      "Sección nueva": "New section",
      "Tarea nueva": "New task",
      "Idea nueva": "New idea",
      "Ver detalle": "Show details",
      "No se pudo dibujar el diagrama.": "The diagram could not be drawn.",
      "Colores": "Colors",
      "Pinta todo el diagrama. Queda escrito en el bloque.": "Colors the whole diagram. It is written into the block.",
      "Por defecto": "Default",
      "Insertar plantilla": "Insert template",
      "Elegí un tipo. Reemplaza todo el diagrama.": "Pick a type. It replaces the whole diagram.",
      "Gris": "Gray",
      "Tinta": "Ink",
      "El diagrama está vacío.": "The diagram is empty.",
      "Escribí el código o elegí una plantilla.": "Type the code or pick a template.",
      "No se reconoce el tipo de diagrama.": "The diagram type is not recognized.",
      "La primera línea dice cuál es, por ejemplo `graph TD` o `sequenceDiagram`.": "The first line says which one it is, for example `graph TD` or `sequenceDiagram`.",
      "La fecha {a} no es válida.": "The date {a} is not valid.",
      "Las fechas van con el formato {b}.": "Dates use the format {b}.",
      "{a} quedó al nivel del tema central.": "{a} sits at the level of the central topic.",
      "Dale más sangría para que cuelgue de una rama. Solo puede haber un tema central.": "Indent it further so it hangs from a branch. There can be only one central topic.",
      "A este bloque le falta su cierre.": "This block is never closed.",
      "Agregá una línea que diga `end` donde termina.": "Add a line that says `end` where it finishes.",
      "A este bloque le falta la llave que lo cierra.": "This block is missing its closing brace.",
      "Agregá una línea con `}` donde termina.": "Add a line with `}` where it finishes.",
      "Falta cerrar las comillas.": "The quotes are not closed.",
      "Falta cerrar el corchete.": "The bracket is not closed.",
      "Cada `[` lleva su `]`, por ejemplo `A[Texto]`.": "Every `[` needs its `]`, for example `A[Text]`.",
      "Falta cerrar el paréntesis.": "The parenthesis is not closed.",
      "Cada `(` lleva su `)`, por ejemplo `A(Texto)`.": "Every `(` needs its `)`, for example `A(Text)`.",
      "Falta cerrar la llave.": "The brace is not closed.",
      "Cada `{` lleva su `}`, por ejemplo `A{Texto}`.": "Every `{` needs its `}`, for example `A{Text}`.",
      "La línea quedó incompleta.": "This line is incomplete.",
      "No se esperaba {a} acá.": "{a} was not expected here.",
      "Un color se escribe así: `style A fill:#fde68a`.": "A color is written like this: `style A fill:#fde68a`.",
      "A la flecha le falta el destino.": "The arrow has no target.",
      "Escribí hacia dónde va, por ejemplo {b}.": "Type where it goes, for example {b}.",
      "Esta línea necesita una flecha.": "This line needs an arrow.",
      "Por ejemplo {b}.": "For example {b}.",
      "Sobra texto después de {b}.": "There is extra text after {b}.",
      "Borrá {a}, o unilo con una flecha.": "Delete {a}, or join it with an arrow.",
      "Al participante le falta el nombre.": "The participant has no name.",
      "Por ejemplo `participant A`.": "For example `participant A`.",
      "Al mensaje le falta el texto.": "The message has no text.",
      "Va después de dos puntos, por ejemplo {b}.": "It goes after a colon, for example {b}.",
      "Las transiciones se escriben con `-->`.": "Transitions are written with `-->`.",
      "A la relación le falta la otra clase.": "The relation is missing the other class.",
      "A la relación le falta el nombre.": "The relation has no name.",
      "Al atributo le falta una parte.": "The attribute is missing a part.",
      "Cada atributo lleva tipo y nombre, por ejemplo `string id`.": "Each attribute has a type and a name, for example `string id`.",
      "A la tarea le faltan los datos.": "The task has no data.",
      "Van después de dos puntos, por ejemplo {b}.": "They go after a colon, for example {b}.",
      "Esta porción no se pudo leer.": "This slice could not be read.",
      "Cada una va con el nombre entre comillas y un número: `\"Nombre\" : 10`.": "Each one has its name in quotes and a number: `\"Name\" : 10`.",
      "Cada período va así: `2024 : Evento`.": "Each period goes like this: `2024 : Event`.",
      "Empezá con `digraph { a -> b }`.": "Start with `digraph { a -> b }`.",
      "No se reconoce el comienzo del diagrama.": "The start of the diagram is not recognized.",
      "La primera línea empieza con `digraph` o con `graph`.": "The first line starts with `digraph` or `graph`.",
      "En un `graph` las líneas se unen con `--`.": "In a `graph`, lines are joined with `--`.",
      "Para usar flechas `->`, la primera línea tiene que decir `digraph`.": "To use `->` arrows, the first line has to say `digraph`.",
      "En un `digraph` las flechas se escriben `->`.": "In a `digraph`, arrows are written `->`.",
      "Para unir con `--`, la primera línea tiene que decir `graph`.": "To join with `--`, the first line has to say `graph`.",
      "Los atributos van entre corchetes, por ejemplo `a [label=\"Texto\"]`.": "Attributes go in brackets, for example `a [label=\"Text\"]`.",
      "Falta la llave que cierra el diagrama.": "The brace that closes the diagram is missing.",
      "Agregá `}` al final.": "Add `}` at the end.",
      "A la línea le falta el destino.": "The line has no target.",
      "Estructuras": "Structures",
      "Letras griegas": "Greek letters",
      "Relaciones": "Relations",
      "Operaciones": "Operations",
      "Flechas": "Arrows",
      "Fracción": "Fraction",
      "Potencia": "Power",
      "Subíndice": "Subscript",
      "Raíz": "Root",
      "Raíz enésima": "Nth root",
      "Sumatoria": "Sum",
      "Integral": "Integral",
      "Límite": "Limit",
      "Matriz": "Matrix",
      "Sistema de ecuaciones": "System of equations",
      "Paréntesis que crecen": "Stretching parentheses",
      "Texto": "Text",
      "Igual": "Equal",
      "Distinto": "Not equal",
      "Aproximado": "Approximately",
      "Menor o igual": "Less than or equal",
      "Mayor o igual": "Greater than or equal",
      "Mucho menor": "Much less",
      "Mucho mayor": "Much greater",
      "Equivalente": "Equivalent",
      "Proporcional": "Proportional",
      "Parecido": "Similar",
      "Pertenece": "Belongs to",
      "No pertenece": "Does not belong to",
      "Subconjunto": "Subset",
      "Subconjunto o igual": "Subset or equal",
      "Más o menos": "Plus or minus",
      "Por": "Times",
      "Dividido": "Divided by",
      "Punto": "Dot",
      "Infinito": "Infinity",
      "Derivada parcial": "Partial derivative",
      "Nabla": "Nabla",
      "Unión": "Union",
      "Intersección": "Intersection",
      "Para todo": "For all",
      "Existe": "Exists",
      "Puntos suspensivos": "Ellipsis",
      "Vector": "Vector",
      "Promedio": "Mean",
      "Hacia la derecha": "Right",
      "Hacia la izquierda": "Left",
      "En los dos sentidos": "Both ways",
      "Implica": "Implies",
      "Implicado por": "Implied by",
      "Si y solo si": "If and only if",
      "Corresponde a": "Maps to",
      "Hacia arriba": "Up",
      "Hacia abajo": "Down",
      "Editar fórmula": "Edit formula",
      "Fórmula nueva": "New formula",
      "Eliminar la fórmula": "Delete the formula",
      "Escribí la fórmula, o armala con las piezas de arriba": "Type the formula, or build it with the pieces above",
      "La fórmula se va a ver acá": "The formula will show here",
      "No se pudo dibujar la fórmula.": "The formula could not be drawn.",
      "No existe el comando {a}.": "The command {a} does not exist.",
      "¿Quisiste escribir {b}?": "Did you mean {b}?",
      "Revisá cómo está escrito. Mayúsculas y minúsculas cuentan.": "Check the spelling. Upper and lower case matter.",
      "Hay dos potencias seguidas.": "There are two powers in a row.",
      "Agrupá con llaves, por ejemplo `a^{b^c}`.": "Group with braces, for example `a^{b^c}`.",
      "Hay dos subíndices seguidos.": "There are two subscripts in a row.",
      "Agrupá con llaves, por ejemplo `a_{i_j}`.": "Group with braces, for example `a_{i_j}`.",
      "Falta lo que va después de {a}.": "Something is missing after {a}.",
      "A `\\left` le falta su `\\right`.": "`\\left` is missing its `\\right`.",
      "Van de a pares, por ejemplo `\\left( x \\right)`.": "They come in pairs, for example `\\left( x \\right)`.",
      "No existe el entorno {a}.": "The environment {a} does not exist.",
      "Probá con `matrix`, `pmatrix` o `cases`.": "Try `matrix`, `pmatrix` or `cases`.",
      "{a} termina con {b}.": "{a} ends with {b}.",
      "Los dos llevan el mismo nombre.": "Both take the same name.",
      "Falta cerrar {a}.": "{a} is never closed.",
      "Agregá {b} al final.": "Add {b} at the end.",
      "Sobra una llave `}`.": "There is one `}` too many.",
      "Cada `}` cierra una `{` que se abrió antes.": "Every `}` closes a `{` opened before it.",
      "`&` solo va dentro de una matriz o un sistema.": "`&` only goes inside a matrix or a system.",
      "Para escribir el signo, usá `\\&`.": "To write the sign itself, use `\\&`.",
      "Falta cerrar una llave.": "A brace is not closed.",
      "Cada `{` lleva su `}`.": "Every `{` needs its `}`.",
      "A {a} le falta una parte.": "{a} is missing a part.",
      "Lleva dos, por ejemplo `\\frac{1}{2}`.": "It takes two, for example `\\frac{1}{2}`.",
      "Cada parte va entre llaves.": "Each part goes in braces.",
      "La fórmula tiene un error.": "The formula has an error.",
      "Está cerca de {a}.": "It is near {a}.",
  };
  let current = 'es';
  function setLang(pref) {
    if (pref === 'es' || pref === 'en') current = pref;
    else {
      // En la web, "automático" sigue a la portada: inglés, o español si se eligió ahí.
      if (typeof window !== 'undefined' && window.__MDT_WEB) { let site = ''; try { site = localStorage.getItem('mdtools:site-lang') || ''; } catch (e) { /* sin almacenamiento */ } current = site === 'es' ? 'es' : 'en'; return current; }
      let ui = '';
      try { ui = chrome.i18n.getUILanguage(); } catch (e) { ui = (typeof navigator !== 'undefined' && navigator.language) || ''; }
      current = /^es\b/i.test(ui) ? 'es' : 'en';
    }
    return current;
  }
  function t(text, vars) {
    let out = current === 'en' && Object.prototype.hasOwnProperty.call(EN, text) ? EN[text] : text;
    if (vars) for (const k in vars) out = out.split('{' + k + '}').join(vars[k]);
    return out;
  }
  const lang = () => current;

  // Servidor de sincronización de esta versión. Vacío: la nube no aparece.
  const CLOUD_URL = 'https://sync.sharpmd.app';
  // Dirección pública de la app web: es la que llevan los enlaces para compartir.
  const WEB_APP_URL = 'https://sharpmd.app/src/app.html';
  const SPONSOR_URL = 'https://ko-fi.com/surlabs';
  // El mismo número que manifest.json: en la web no hay manifiesto del que leerlo. Una prueba falla si no coinciden.
  const VERSION = '2.43.0';

  root.LMD = { VERSION, PLUGIN_HELP, SPONSOR_URL, CLOUD_URL, WEB_APP_URL, CODE_COLORS, DEFAULTS, PLUGIN_LABELS, ACCENTS, FONTS, merge, load, save, patch, setLang, t, lang };
})(typeof self !== 'undefined' ? self : this);
